### ISSUE TITLE
Wrong changer type saved

### ISSUE THREAD

**Issue by zahov99** [Antonrom00/laravel-model-changes-history#5]
https://github.com/Antonrom00/laravel-model-changes-history/blob/9fbeaa4c69ec7c26becef7245725bf3f78dc277e/src/Services/ChangesHistoryService.php#L35

Currently its:
'changer_type' => $changer ? $modelType : null,

Probably it should be:
'changer_type' => $changer ? get_class($changer): null,

**Comment by Antonrom00** [comment]
Yes, this is a mistake, thank you. I fixed it.

**Comment by zahov99** [comment]
Thanks!
